import React from "react";
import Spinner from "./Spinner";
import { BrowserHeader } from "./BrowserHeader";
import Autosuggest from "react-autosuggest";
import { LoadManifestModal } from "./LoadManifestModal";

interface Props {
  loaded: boolean,
  onChangeManifestUrl: (url: string) => void
}

export const GraphBrowserLoader = ({ loaded, onChangeManifestUrl }: Props) => {
  return (
    <div>
      <div className="container">
        {loaded ? (
        <div className="row search-bar">
          <div className="col s12">
          <div className="card">
            <div className="card-content">
              <div className="card-title">
                Welcome to Dagger Browser
              </div>
              Dagger Browser is a simple tool for easily navigating a project's Dagger graph. The graph data is generated by a Dagger SPI plugin and supplied via a JSON manifest file.
              <div className="center-align">
              <LoadManifestModal 
                onChangeManifestUrl={onChangeManifestUrl}
                trigger={<a className="btn red lighten-2" href="#">Load manifest from URL</a>}/>
              </div>
            </div>
          </div>            
          </div>
        </div>
        ) : (
        <div className="row">
          <div className="col s12 center-align">         
            <Spinner/>
          </div>
        </div>  
        )}
      </div>    
    </div>
  );
};

export default GraphBrowserLoader;
